import { Inter } from "next/font/google";
import { dir } from 'i18next'
import { languages } from '../i18n/setting'

import "../globals.css";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

const inter = Inter({
  subsets: ["cyrillic"],
  variable: "--font-inter",
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,params: { lng }}) {
  return (
    <html lang={lng}>
      <head />
      <body className={`${inter.variable}`}>
        <main>
        {children}
        </main>
      </body>
    </html>
  )
}