import { Inter } from "next/font/google";
import "@/app/globals.css";

import { dir } from 'i18next'
import { languages } from '../i18n/settings'

const inter = Inter({
  subsets: ["cyrillic"],
  variable: "--font-inter",
  weight: ['400', '500', '600', '700', '800'],
});

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lng }}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${inter.variable}`}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}